"use client";

import * as React from "react";
import Link from "next/link";
import { FileSearch, Lock } from "lucide-react";

import { Button, Card, CardContent } from "@/components/ui";
import { findCajaMovement, type CajaMovement } from "@/features/caja/caja-data";
import { BackLink, CashJornadaCard, MovementDetailHeader, MovementInfoCard, MovementResultCard } from "./movement-detail-parts";
import { CashAdjustmentDetail } from "./cash-adjustment-detail";
import { MovementReceiptSection } from "./movement-receipt-section";

/**
 * Cash Movement Detail — the auditable record behind one INTERNAL Caja
 * movement (no `operationCode`). A movement generated by a customer
 * operation keeps its existing destination, `/worker/operaciones/[codigo]`
 * (§18); this route only ever resolves the other kind.
 *
 * Client Component for the same reason Operation Detail is one: a movement
 * created moments ago by Ajustar efectivo or Registrar fondeo inicial only
 * exists in the browser's own copy of the mock ledger, mutated client-side —
 * a Server Component here would render the not-found card for a movement
 * that genuinely exists in this session.
 *
 * `MovementSpecificDetail` is a plain typed switch on `concepto`, not a
 * plugin/registry framework — "Ajuste de efectivo" is the only concept with
 * a specialized card today; every other internal concept (Fondeo inicial,
 * and any future one) falls back to the common cards only, so nothing is
 * fabricated for a concept this screen doesn't specifically know about.
 */
export function CashMovementDetailView({ movementId }: { movementId: string }): React.JSX.Element {
  const movement = findCajaMovement(movementId);

  if (!movement) return <MovementNotFound movementId={movementId} />;

  return (
    <div className="flex flex-col gap-6">
      <BackLink />
      <MovementDetailHeader movement={movement} />

      <div className="grid grid-cols-1 items-start gap-6 xl:grid-cols-2">
        <div className="flex flex-col gap-6">
          <MovementInfoCard movement={movement} />
          <CashJornadaCard movement={movement} />
        </div>

        <div className="flex flex-col gap-6">
          <MovementSpecificDetail movement={movement} />
          <MovementResultCard movement={movement} />
        </div>
      </div>

      <MovementReceiptSection movement={movement} />

      <p className="flex items-center justify-center gap-2 pb-2 text-caption text-text-secondary print:hidden">
        <Lock className="size-3.5 shrink-0" aria-hidden="true" />
        La información de este movimiento está protegida y solo puede ser vista por personal
        autorizado.
      </p>
    </div>
  );
}

/**
 * The specialized card for concepts this screen knows how to explain in
 * depth. Returns nothing (not a placeholder) for any other concept — the
 * common cards already say everything genuinely available (§14).
 */
function MovementSpecificDetail({ movement }: { movement: CajaMovement }): React.JSX.Element | null {
  if (movement.concepto === "Ajuste de efectivo" || movement.concepto === "Ajuste de cierre") {
    return <CashAdjustmentDetail movement={movement} />;
  }
  return null;
}

/**
 * An unrecognised movement id renders a graceful card rather than a hard
 * 404 — the same pattern already established by Operation Detail, since
 * movement ids are a growing runtime dataset a worker could mistype or
 * revisit via a stale link.
 */
function MovementNotFound({ movementId }: { movementId: string }) {
  return (
    <div className="flex flex-col gap-6">
      <BackLink />
      <Card>
        <CardContent className="flex flex-col items-center gap-2 py-16 text-center">
          <span
            aria-hidden="true"
            className="grid size-12 place-items-center rounded-control bg-primary-subtle text-primary"
          >
            <FileSearch className="size-6" />
          </span>
          <p className="mt-2 text-section-title text-text-primary">Movimiento no encontrado</p>
          <p className="max-w-sm text-body text-text-secondary">
            No hay ningún movimiento de caja con el identificador{" "}
            <span className="pc-numeric font-medium text-text-primary">{movementId}</span>.
          </p>
          <Button className="mt-4" asChild>
            <Link href="/worker/caja">Volver a Caja</Link>
          </Button>
        </CardContent>
      </Card>
    </div>
  );
}
