import { test, expect, type Page } from "@playwright/test";

/**
 * Worker Caja — Cash Movement Detail (/worker/caja/movimientos/[id]).
 *
 * An internal Caja movement (no `operationCode`) — Ajuste de efectivo,
 * Fondeo inicial, and any future internal concept — gets a "Ver detalle"
 * action in the movements table leading here. A movement generated by a
 * customer operation keeps its existing destination
 * (`/worker/operaciones/[codigo]`) and never shows a duplicate action.
 *
 * `abrirJornada`/`ajustarEfectivo` mutate a client-side, in-memory module —
 * a hard navigation (`page.goto`) re-fetches a fresh server render and loses
 * that state, so any test that needs a movement THIS session just created
 * reaches it by clicking links, never by `page.goto`. The pre-seeded mock
 * ledger (Apertura de caja, Fondeo adicional, the static Ajuste de efectivo
 * fixture) is plain module-level data, so it renders identically from a
 * fresh `page.goto` too.
 */

/** Visible text only — the print-only comprobante repeats most labels/values. */
function onScreen(page: Page, text: string | RegExp) {
  return page.getByText(text).filter({ visible: true });
}

async function openJornada(page: Page, fondos: Record<string, string> = { EUR: "1200" }) {
  await page.goto("/worker/caja/fondeo-inicial");
  for (const [currency, value] of Object.entries(fondos)) {
    await page.getByLabel(`Fondo inicial en ${currency}`).fill(value);
  }
  await page.getByRole("button", { name: "Continuar" }).click();
  await page.getByRole("button", { name: "Confirmar y abrir caja" }).click();
  await expect(page.getByRole("heading", { name: "Caja abierta correctamente" })).toBeVisible({
    timeout: 5000,
  });
}

/** From the Caja main screen, opens the Ajustar efectivo tile. */
async function goToAjustarEfectivoFromCaja(page: Page) {
  await page.getByRole("link", { name: /Ajustar efectivo/ }).click();
  await expect(page.getByRole("heading", { name: "Ajustar efectivo" })).toBeVisible();
}

/** From the Ajustar efectivo form, fills and confirms one adjustment. */
async function fillAndConfirmAdjustment(
  page: Page,
  opts: { currency?: string; counted: string; motivo?: string; observaciones?: string },
) {
  await page.getByRole("button", { name: /^Moneda:/ }).click();
  await page.getByRole("option", { name: new RegExp(`^${opts.currency ?? "EUR"}`) }).click();
  await page.getByLabel("Efectivo contado").fill(opts.counted);
  await page.getByLabel("Motivo del ajuste").click();
  await page.getByRole("option", { name: opts.motivo ?? "Faltante detectado", exact: true }).click();
  if (opts.observaciones) await page.locator("#ajuste-observaciones").fill(opts.observaciones);

  await page.getByRole("button", { name: "Continuar" }).click();
  await expect(page.getByRole("heading", { name: "Revisar ajuste de efectivo" })).toBeVisible();
  await page.getByRole("button", { name: "Confirmar ajuste" }).click();
  await expect(page.getByRole("heading", { name: "Ajuste registrado correctamente" })).toBeVisible({
    timeout: 3000,
  });
}

/** From the "Caja abierta"/"Ajuste registrado" result screen (has "Ir a Caja"), completes one adjustment. */
async function makeAdjustment(
  page: Page,
  opts: { currency?: string; counted: string; motivo?: string; observaciones?: string },
) {
  await page.getByRole("link", { name: "Ir a Caja" }).click();
  await goToAjustarEfectivoFromCaja(page);
  await fillAndConfirmAdjustment(page, opts);
}

/**
 * Clicks "Ver detalle" on the first movements-table row whose Concepto
 * matches, via a hard `page.goto("/worker/caja")` first — safe only for the
 * pre-seeded, module-level mock ledger (Apertura de caja, Fondeo adicional,
 * the static Ajuste de efectivo fixture), never for a movement THIS test
 * just created client-side. Use `goToCajaAndOpenDetail` after any
 * `openJornada`/`makeAdjustment` call instead.
 */
async function openDetailFor(page: Page, concepto: string) {
  await page.goto("/worker/caja");
  await openDetailForFromCaja(page, concepto);
}

async function openDetailForFromCaja(page: Page, concepto: string) {
  const movementsTable = page.getByRole("table").nth(1);
  const row = movementsTable.locator("tbody tr").filter({ hasText: concepto }).first();
  await row.getByRole("link", { name: "Ver detalle" }).click();
  await expect(page.getByRole("heading", { name: "Movimiento de caja" })).toBeVisible();
}

/**
 * Same as `openDetailFor`, but reaches Caja through the "Ir a Caja" link
 * already on screen (a client-side navigation) instead of a hard reload —
 * the only safe way to view a movement created earlier in the same test.
 */
async function goToCajaAndOpenDetail(page: Page, concepto: string) {
  await page.getByRole("link", { name: "Ir a Caja" }).click();
  await openDetailForFromCaja(page, concepto);
}

test.describe("caja movements table — Acciones column", () => {
  test("renders an Acciones column header", async ({ page }) => {
    await page.goto("/worker/caja");
    const movementsTable = page.getByRole("table").nth(1);
    await expect(movementsTable.getByRole("columnheader", { name: "Acciones" })).toBeVisible();
  });

  test("an internal movement (no operationCode) shows Ver detalle, Operación stays —", async ({
    page,
  }) => {
    await page.goto("/worker/caja");
    const movementsTable = page.getByRole("table").nth(1);
    const row = movementsTable.locator("tbody tr").filter({ hasText: "Ajuste de efectivo" }).first();

    await expect(row.getByRole("link", { name: "Ver detalle" })).toBeVisible();
    await expect(row.locator("td").nth(1)).toHaveText("—");
  });

  test("a movement with operationCode links to Operation Detail and shows no duplicate Ver detalle", async ({
    page,
  }) => {
    await page.goto("/worker/caja");
    const movementsTable = page.getByRole("table").nth(1);
    const row = movementsTable.locator("tbody tr").filter({ hasText: "PC-260818-005004" }).first();

    await expect(row.getByRole("link", { name: "PC-260818-005004" })).toHaveAttribute(
      "href",
      "/worker/operaciones/PC-260818-005004",
    );
    await expect(row.getByRole("link", { name: "Ver detalle" })).toHaveCount(0);
  });

  test("Ver detalle navigates to /worker/caja/movimientos/[id]", async ({ page }) => {
    await openDetailFor(page, "Ajuste de efectivo");
    await expect(page).toHaveURL(/\/worker\/caja\/movimientos\/CM-/);
  });
});

test.describe("cash movement detail — unknown id", () => {
  test("fails gracefully with a not-found card, not a hard 404", async ({ page }) => {
    await page.goto("/worker/caja/movimientos/CM-000000-999999");

    await expect(page.getByText("Movimiento no encontrado")).toBeVisible();
    await expect(page.getByText("CM-000000-999999")).toBeVisible();
    await page.getByRole("link", { name: "Volver a Caja" }).first().click();
    await expect(page).toHaveURL(/\/worker\/caja$/);
  });
});

test.describe("cash movement detail — Ajuste de efectivo (static fixture)", () => {
  test.beforeEach(async ({ page }) => {
    await openDetailFor(page, "Ajuste de efectivo");
  });

  test("shows the movementId prominently under the title", async ({ page }) => {
    await expect(onScreen(page, /^CM-\d{6}-\d{6}$/).first()).toBeVisible();
  });

  test("shows Concepto = Ajuste de efectivo", async ({ page }) => {
    await expect(onScreen(page, "Ajuste de efectivo").first()).toBeVisible();
  });

  test("shows the Salida badge as text, not colour alone", async ({ page }) => {
    await expect(onScreen(page, "Salida").first()).toBeVisible();
  });

  test("shows the currency with its CurrencyFlag, aria-hidden and never emoji", async ({ page }) => {
    await expect(onScreen(page, "EUR · Euro")).toBeVisible();
    const flag = page.locator("svg[data-currency-flag]").first();
    await expect(flag).toHaveAttribute("aria-hidden", "true");
    const hasRegionalIndicator = await page.evaluate(() =>
      /[\u{1F1E6}-\u{1F1FF}]/u.test(document.body.textContent ?? ""),
    );
    expect(hasRegionalIndicator).toBe(false);
  });

  test("shows the signed amount", async ({ page }) => {
    await expect(onScreen(page, /−15,00 EUR|-15,00 EUR/).first()).toBeVisible();
  });

  test("shows the timestamp as dd/MM/yyyy · HH:mm", async ({ page }) => {
    await expect(onScreen(page, /\d{2}\/\d{2}\/\d{4} · \d{2}:\d{2}/).first()).toBeVisible();
  });

  test("shows Caja and Trabajador", async ({ page }) => {
    await expect(onScreen(page, "Caja 03").first()).toBeVisible();
    await expect(onScreen(page, "Juan Pérez").first()).toBeVisible();
  });

  test("shows the historical jornada opening context, not today's live jornada", async ({ page }) => {
    await expect(onScreen(page, "Abierta").first()).toBeVisible();
    await expect(onScreen(page, /Abierta el: \d{2}\/\d{2}\/\d{4} · \d{2}:\d{2}/)).toBeVisible();
  });

  test("shows Saldo registrado antes del ajuste and Efectivo contado", async ({ page }) => {
    await expect(onScreen(page, "Saldo registrado antes del ajuste")).toBeVisible();
    await expect(onScreen(page, "Efectivo contado")).toBeVisible();
  });

  test("shows Diferencia with explicit negative sign and error semantics", async ({ page }) => {
    await expect(onScreen(page, "Diferencia")).toBeVisible();
    await expect(onScreen(page, /−15,00 EUR|-15,00 EUR/).first()).toBeVisible();
  });

  test("shows Motivo", async ({ page }) => {
    await expect(onScreen(page, "Motivo")).toBeVisible();
    await expect(onScreen(page, "Faltante detectado")).toBeVisible();
  });

  test("shows Observaciones when present", async ({ page }) => {
    await expect(onScreen(page, "Observaciones")).toBeVisible();
    await expect(onScreen(page, "Conteo verificado nuevamente.")).toBeVisible();
  });

  test("Resultado del movimiento shows Saldo anterior, Movimiento and Saldo resultante", async ({
    page,
  }) => {
    await expect(onScreen(page, "Resultado del movimiento")).toBeVisible();
    await expect(onScreen(page, "Saldo anterior")).toBeVisible();
    await expect(onScreen(page, "Movimiento").first()).toBeVisible();
    await expect(onScreen(page, "Saldo resultante")).toBeVisible();
  });

  test("does not render an Operación relacionada card", async ({ page }) => {
    await expect(page.getByText("Operación relacionada")).toHaveCount(0);
  });

  test('"Imprimir comprobante" triggers the existing browser-print mechanism', async ({ page }) => {
    let printed = false;
    await page.exposeFunction("__notifyPrint", () => {
      printed = true;
    });
    await page.evaluate(() => {
      window.print = () => (window as unknown as { __notifyPrint: () => void }).__notifyPrint();
    });
    await page.getByRole("button", { name: "Imprimir comprobante" }).click();
    expect(printed).toBe(true);
  });
});

test.describe("cash movement detail — a live positive adjustment", () => {
  test("a positive difference keeps its explicit + sign and success semantics", async ({ page }) => {
    await openJornada(page, { EUR: "1200" });
    await makeAdjustment(page, { currency: "EUR", counted: "1220", motivo: "Sobrante detectado" });
    await goToCajaAndOpenDetail(page, "Ajuste de efectivo");

    await expect(onScreen(page, "+20,00 EUR").first()).toBeVisible();
  });
});

test.describe("cash movement detail — Fondeo inicial (live)", () => {
  test("resolves and shows only genuinely available common movement information", async ({ page }) => {
    await openJornada(page, { EUR: "1200" });
    await goToCajaAndOpenDetail(page, "Fondeo inicial");

    await expect(page.getByRole("heading", { name: "Movimiento de caja" })).toBeVisible();
    await expect(onScreen(page, "Fondeo inicial").first()).toBeVisible();
    await expect(onScreen(page, "Entrada").first()).toBeVisible();
    await expect(onScreen(page, "Saldo resultante")).toBeVisible();

    // No adjustment-specific fields are fabricated for this concept.
    await expect(page.getByText("Detalle del ajuste")).toHaveCount(0);
    await expect(page.getByText("Diferencia")).toHaveCount(0);
    await expect(page.getByText("Motivo")).toHaveCount(0);
    await expect(page.getByText("Observaciones")).toHaveCount(0);
    // Fondeo inicial has no meaningful "before" — "Saldo anterior" is not fabricated.
    await expect(page.getByText("Saldo anterior")).toHaveCount(0);
  });
});

test.describe("cash movement detail — generic internal fallback", () => {
  test("a concept with no specialized component shows only common fields, nothing fabricated", async ({
    page,
  }) => {
    // "Fondeo adicional" (the static mock fixtures) has no specialized
    // detail component either — the same generic fallback path as Fondeo
    // inicial, exercised here against the pre-seeded, non-live data.
    await openDetailFor(page, "Fondeo adicional");

    await expect(page.getByRole("heading", { name: "Movimiento de caja" })).toBeVisible();
    await expect(page.getByText("Detalle del ajuste")).toHaveCount(0);
    await expect(page.getByText("Motivo")).toHaveCount(0);
    await expect(page.getByText("Observaciones")).toHaveCount(0);
  });
});

test.describe("cash movement detail — historical immutability", () => {
  test("does not change when the current Caja balance changes later", async ({ page }) => {
    await openJornada(page, { EUR: "1200" });
    await makeAdjustment(page, { currency: "EUR", counted: "1185", motivo: "Faltante detectado" });

    await page.getByRole("link", { name: "Ir a Caja" }).click();
    const movementsTable = page.getByRole("table").nth(1);
    const firstAdjustmentHref = await movementsTable
      .locator("tbody tr")
      .filter({ hasText: "Ajuste de efectivo" })
      .first()
      .getByRole("link", { name: "Ver detalle" })
      .getAttribute("href");
    expect(firstAdjustmentHref).toBeTruthy();

    // A second adjustment on the same currency changes the CURRENT EUR balance.
    await goToAjustarEfectivoFromCaja(page);
    await fillAndConfirmAdjustment(page, { currency: "EUR", counted: "1160", motivo: "Faltante detectado" });

    // The first movement's own historical record must still read as it did —
    // reached via the same in-page client-side Link, never a hard reload,
    // since the mutated ledger only ever exists in this page's own JS realm.
    await page.getByRole("link", { name: "Ir a Caja" }).click();
    await page.locator(`a[href="${firstAdjustmentHref}"]`).first().click();
    await expect(page.getByRole("heading", { name: "Movimiento de caja" })).toBeVisible();

    await expect(onScreen(page, "1.200,00 EUR").first()).toBeVisible();
    await expect(onScreen(page, "1.185,00 EUR").first()).toBeVisible();
    await expect(onScreen(page, "−15,00 EUR").or(onScreen(page, "-15,00 EUR")).first()).toBeVisible();
  });
});

test.describe("cash movement detail — layout", () => {
  for (const width of [1440, 1280]) {
    test(`fits without page-level horizontal scroll at ${width}px`, async ({ page }) => {
      await page.setViewportSize({ width, height: 900 });
      await openDetailFor(page, "Ajuste de efectivo");

      const overflows = await page.evaluate(
        () => document.documentElement.scrollWidth > document.documentElement.clientWidth,
      );
      expect(overflows).toBe(false);
    });
  }

  test("zero console errors", async ({ page }) => {
    const errors: string[] = [];
    page.on("pageerror", (error) => errors.push(String(error)));
    page.on("console", (message) => {
      if (message.type() === "error") errors.push(message.text());
    });

    await openDetailFor(page, "Ajuste de efectivo");
    await page.getByRole("link", { name: "Volver a Caja" }).click();

    expect(errors).toEqual([]);
  });
});
